"""Adicionando colunas ao modelo Paciente

Revision ID: 31bf458bf7e5
Revises: c4928c06caa3
Create Date: 2024-08-22 16:02:36.899452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bf458bf7e5'
down_revision = 'c4928c06caa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=200), nullable=False))

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidade', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('crm', sa.String(length=20), nullable=False))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('endereco')
        batch_op.drop_column('data_nascimento')

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_column('crm')
        batch_op.drop_column('especialidade')

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
